# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: All tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      neo4j:
        image: neo4j
        ports:
          - 7687
        env:
          NEO4J_AUTH: neo4j/test

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
    - name: Send coverage xml artifact to codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./build/reports/jacoco/test/jacocoTestReport.xml
        fail_ci_if_error: false
